spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/citronix
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework: DEBUG
